### ISSUE TITLE
BigDecimalField does not follow --vaadin-text-field-default-width

### ISSUE THREAD

**Issue by eiswind** [vaadin/vaadin-lumo-styles#89] opened 2020-07-04 12:13 UTC
I don't know if this is a component or a lumo issue, so please move it if necessary,

I found that setting --vaadin-text-field-default-width has no effect on BigDecimalField.

(Vaadin 14.2.3, Lumo 1.5.0)

**Comment by jouni** [comment] 2020-08-06 13:06
No wonder it doesn’t follow it: the host is fixed at 8em 😅 (no idea why)
https://github.com/vaadin/vaadin-text-field-flow/blob/master/vaadin-text-field-flow/src/main/resources/META-INF/resources/frontend/vaadin-big-decimal-field.js#L29-L31

**Comment by jouni** [comment] 2020-08-06 13:12
Apparently it’s by design (didn’t remember that): https://github.com/vaadin/vaadin-text-field-flow/pull/254

I’m closing this as it works as intended. Follow and upvote https://github.com/vaadin/vaadin-text-field/issues/357 instead.

**Closed by jouni** 2020-08-06 13:12 UTC
Labels: Impact: Low, Severity: Minor, bug
